name: Update Playlist

on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'Stream URL'
        required: true
      ACTION:
        description: 'Action (add or delete)'
        required: true

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Update playlist file
      run: |
        FILE=playlist-urls.txt
        NEW_URL=${{ github.event.inputs.URL }}
        ACTION=${{ github.event.inputs.ACTION }}
        
        if [ "$ACTION" == "add" ]; then
          if ! grep -Fxq "$NEW_URL" "$FILE"; then
            echo "$NEW_URL" >> "$FILE"
          fi
        elif [ "$ACTION" == "delete" ]; then
          sed -i "/$NEW_URL/d" "$FILE"
        fi
        
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add $FILE
        git commit -m "Update playlist with $ACTION URL: $NEW_URL"
        git push
